# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20180629_1457'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([]),
        ),
    ]
